# source files in this project (main.cpp is automatically assumed)
SOURCES :=

# header files in this project
HEADERS :=oled.hpp oled_init.hpp drawable.hpp ball.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due